# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: tskit.dev
email: 	admin@tskit.dev
description: The open source tree sequence community

baseurl: "tskit-site" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-font-awesome-sass

sass:
  sass_dir: _sass

# TODO turn on stricter
# liquid:
#   error_mode: warn
#   strict_variables: true
#   strict_filters: true

collections:
  software:
    output: true
  news:
    output: true
  resources:
    output: false

pubs:
  # TODO update the categories. We may want to remove this entirely.
  categories:
    - key: core
      title: Core tree sequence

  pubs:
    - doi: 10.1038/s41588-019-0483-y
      category: core
      notes: |
        Start here if you're new to tree sequences. This paper introduces
        <a href="/tsinfer.html">tsinfer</a>, the method to infer tree sequence
        topologies from genetic variation data.
        Please see the
        <a href="https://www.biorxiv.org/content/10.1101/458067v1">preprint</a>
        if you cannot access the Nature Genetics paper.

    - doi: 10.1534/genetics.120.303253
      category: core
      notes: |
        This paper shows that we can think about any statistic that works on
        sequence data in an equivalent (and more powerful) way in terms of the
        underlying trees, and that we can compute these statistics very efficiently.
        Read this paper if you would like more technical details on how the
        underlying data structures work and an introduction to incremental
        tree sequence algorithms.

    - doi: 10.1371/journal.pcbi.1006581
      category: core
      notes: |
        Forwards-in-time simulations are very flexible but also usually very CPU
        intensive. This paper shows how we used tree sequences to make
        forwards-in-time simulations both more efficient and even more flexible.

    - doi: 10.1111/1755-0998.12968
      category: core
      notes: |
        Continuing on from the 2018 PLOS Computational Biology paper,
        we discuss here how the tree
        sequence recording method was implemented in the powerful
        <a href="https://messerlab.org/slim/">SLiM</a> simulator. We
        show how some simulations are orders of magnitude more efficient
        and examples of the new possibilities that keeping a full
        record of the genetic ancestry makes available.

    - doi: 10.1371/journal.pcbi.1004842
      category: core
      notes: |
        This is where it all started. Here we introduce the
        <a href="/msprime.html">msprime</a> coalescent simulator and
        the core algorithms and data structures that would later
        be separated out into <a href="/tskit.html">tskit</a>.
        Read this paper if you would like to find out more about
        coalescent simulation, or to understand the core tree sequence
        algorithms and theoretical results. <b>Note:</b> much
        of the terminology has been updated since this original publication
        as the models were generalised.

videos:
  - youtube-id: YrZTKjLzZY0
    who: Wilder Wohns
    year: 2020
    where: Phyloseminar
    title: Tree sequence fundamentals

  - youtube-id: yB4uSle66Pw
    who: Yan Wong
    year: 2020
    where: Phyloseminar
    title: Tree sequences and inference

  - youtube-id: yrDSLlssoek
    who: Jerome Kelleher
    title: Inferring the ancestry of everyone
    where: PopGen Vienna
    year: 2020

  - youtube-id: X1GEuQrF1jQ&t=6
    who: Wilder Wohns
    where: MIA Primer
    title: Introduction to the tree sequence toolchain
    year: 2019

  - youtube-id: X1GEuQrF1jQ&t=2825
    who: Jerome Kelleher
    where: MIA
    title: Succinct tree sequences for megasample genomics
    year: 2019

  - youtube-id: MH2b9iU4oUA
    who: Jerome Kelleher
    title: Simulating, storing & processing genetic variation data for millions of samples
    where: MIA
    year: 2017

font-awesome:
  assets: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
